on:
  pull_request:
    branches:
      - develop
      - main

name: TERRAFORM PLAN

jobs:
  develop_plan:
    name: PR Plan - Develop
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'develop'
    with:
      environment: develop
    secrets: inherit

  staging_plan:
    name: PR Plan - Staging
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'main'
    with:
      environment: main
    secrets: inherit