name: trigger_plan
on:
  # pull_request:
  #   branches:
  #     - develop
  #     - main
  workflow_dispatch:
    inputs:
      folder:
        type: string
        description: "ig, gke, serverless, gcp_funtions"
        required: true
jobs:
  develop_plan:
    name: PR Plan - Develop
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'develop'
    with:
      environment: develop
    secrets: inherit

  staging_plan:
    name: PR Plan - Staging
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'main'
    with:
      environment: main
    secrets: inherit
