name: trigger_plan
on:
  # pull_request:
  #   branches:
  #     - develop
  #     - main
  workflow_dispatch:
    inputs:
      folder:
        type: choice
        description: "Select the folder:"
        required: true
        options:
          - ig
          - gke
          - serverless
          - gcp_funtions
jobs:
  develop_plan:
    name: PR Plan - Develop
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'develop'
    with:
      environment: develop
      folder: ${{ github.event.inputs.folder }}
    secrets: inherit

  staging_plan:
    name: PR Plan - Staging
    uses: ./.github/workflows/plan.yml
    if: github.base_ref == 'main'
    with:
      environment: main
      folder: ${{ github.event.inputs.folder }}
    secrets: inherit
